[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "solady/=lib/solady/src/",
    "@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    ]
    solc = '0.8.26'
    optimizer = true
optimizer_runs = 200
evm_version = "london"

[profile.default.fuzz]
runs = 250

[profile.default.invariant]
runs = 250
depth = 20

[profile.ci.fuzz]
runs = 1000

[profile.ci.invariant]
runs = 10000
depth = 50


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

